### ISSUE TITLE
"Please add a @NgModule annotation"

### ISSUE THREAD

**Issue by rimlin** [geoctrl/angular-svg-icons#2]
Hello, after importing `IconModule` to my app module, i had see next error: 
`Error: Unexpected value 'IconModule' imported by the module 'AppModule'. Please add a @NgModule annotation.`. 
I think what this eror is related with https://github.com/angular/angular-cli/issues/6239
Do you have any ideas how to fix it?

**Comment by geoctrl** [comment]
Thanks for opening an issue - I was aware of this, and it's causing different errors for people with different setups.
I'm currently working on a fix to remove babel and simplify the build process (including a fix for this).
Bear with me 😄

**Comment by karan16a** [comment]
Hey! I am facing the same issue. Is there any updates on the bug fix?

**Comment by geoctrl** [comment]
@karan16a - in the middle of the fix - been busy, so I haven't been able to finish it - I'm hoping to have this done by this weekend

**Comment by geoctrl** [comment]
@rimlin @karan16a  just updated the package.
I'm now using angular's recommended way of creating libraries using the `angular-compiler`. Please test it out and let me know how it goes...

Please note that I've updated the package to v2 -> introduced a breaking change, including the implementation steps. Please checkout the README for more info.

**Comment by geoctrl** [comment]
@rimlin if this fix fixes the issue for you, please close this issue - thanks 😄

**Comment by Kamilius** [comment]
> I'm now using angular's recommended way of creating libraries using the angular-compiler

@geoctrl could you reference this `angular's recommended way`?
