### ISSUE TITLE
AoT error using recommended approach 

### ISSUE THREAD

**Issue by nickolas1** [geoctrl/angular-svg-icons#3]
I'm using ng-cli, and when importing an svg spritesheet using ${svgSymbols} in the template it is erroring with "Error encountered resolving symbol values statically. Expression form not supported". Can you recommend an alternative AoT-safe approach to including the svg content?

**Comment by geoctrl** [comment]
I'm not very familiar with Angular's AoT stuff... I use webpack to build all the things.
Looks like AoT has some limitations - check these out:

https://github.com/angular/angular-cli/issues/4956
https://github.com/rangle/angular-2-aot-sandbox#aot-dos-and-donts

If you figure out a solution post it here. If you have a code fix, create a pull request. thanks

**Comment by nickolas1** [comment]
This can be worked around by putting a div in the template to hold the svg and populating its innerHtml during ngOnInit.

```
<div #svgElement></div>
<rest-of-your-app></rest-of-your-app>
```

```
@ViewChild('svgElement') svgElement: ElementRef;

ngOnInit() {
    this.svgElement.nativeElement.innerHtml = svgSymbols;
}
```

**Comment by geoctrl** [comment]
👍  sweet - closing the issue
